### PR TITLE
fix(index): ignore generated code from `jshint`

### PR DESCRIPTION
**Pull request by koningskristof**
jshint-loader expects a dot-notation

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@koningskristof why you lint bundle?

**Comment by koningskristof** [comment]
Not a bundle, but local files that needed to be exposed as global ( legacy project ).

**Comment by evilebottnawi** [comment]
@koningskristof i don't think we should add workaround for legacy projects.

**Comment by koningskristof** [comment]
Besides my current situation is a legacy project.
You are able to use expose-loader to generate a global variable from something that is not a bundle.

**Comment by koningskristof** [comment]
Ok, thanks for considering.
For further reference, I could work around it by enforcing the jshint-loader to run before expose-loader by using { enforce: 'pre' }.

**Comment by evilebottnawi** [comment]
@koningskristof i recommend avoid linting using loaders/plugins - it is increase compilation time, better use for this npm commands and your IDE features

**Comment by koningskristof** [comment]
Thanks for your advice, we have taken it into account !

2018-02-05 12:33 GMT+01:00 Evilebot Tnawi <notifications@github.com>:

**Pull request closed without merging**
