### PR TITLE
fix(core): module resolution in webpack 5 broken due this.context points to module entry directory

### PR DESCRIPTION
**Pull request by Delagen**
…nts to module entry directory

This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

Broken module resolution in webpack 5

### Breaking Changes

Seems missing )

### CODE REVIEW

**Comment by Delagen** [comment]
@evilebottnawi How to do this? multiversion dependencies does not supported by npm? We need both webpack@4 & webpack@5

**Comment by evilebottnawi** [comment]
You can send a PR with test and i will fix CI setup for testing across webpack@4 and webpack@5

**Comment by Delagen** [comment]
@evilebottnawi Add simple test, but cannot test it in webpack5 due stats missing source property. This property present in stats.compilation.modules as _source, but missing in toJson result. Added stats:'verbose' to config but no effect. May be @sokra offer some advice how to get source from stats in updated webpack?

**Comment by Delagen** [comment]
@evilebottnawi ???

**Comment by Delagen** [comment]
Any changes?

**Comment by evilebottnawi** [comment]
Sorry for delay, fixed in the `master`, no you should use the `expose` option for provide exposes, ETA is end of the week

**Comment by Delagen** [comment]
@evilebottnawi When?

**Comment by evilebottnawi** [comment]
@Delagen Some delay, due compatibility with `imports-loader`, `exports-loader` and `expose-loader`, here https://github.com/webpack-contrib/expose-loader/pull/100 progress

**Pull request closed without merging**
