### PR TITLE
feat(index): add resolve method for global (`options.resolver`)

### PR DESCRIPTION
**Pull request by joseym**
A project I'm working on needed to expose multiple globals on the same nested global object for backwards compatibility.

This PR allows the loaders options to take an object with a key of `resolver`, which can be a string or a method. If a method, then it is called with the loaders details as its first parameter. 

```javascript
...
module: {
  rules:   test: /\.js$/, use: [
    {
      loader: 'expose-loader',
      options: {
        resolver: (chunk) => {
          const namespace = chunk.resourcePath.replace(/.*components\/(.*)\.js/, '$1');
          return `Components.${namespace}`
        }
      }
    }
  ]
}
...
```
Alternatively the `resolver` key can be a string:

```javascript
...
{
  loader: 'expose-loader',
  options: {
    resolver: 'Components.legacy'
  }
}
...
```

Or just be set as it has always been:

```javascript
...
{
  loader: 'expose-loader',
  options: 'Components.legacy'
}
...
```

### CODE REVIEW

**Comment by tameraydin** [comment]
Any updates on merging this?

**Comment by joseym** [comment]
**¯\\\_(ツ)\_/¯**

@tameraydin It looks like it was added to the next milestone, which is promising. 

Less promising is the fact that there's also a ticket in there that was created at the beginning of 2015, and was added to the milestone the middle of last year, so who knows when this will actually get merged ...

**Comment by tameraydin** [comment]
Hi @michael-ciniawsky, I see that you have added it to the next milestone recently; can you please update us on the timeline/plans? 
Moreover, how can I (or others) help you on this to speed-up the progress?

**Comment by evilebottnawi** [comment]
Will be solved in the other way, anyway thanks for your PR, we move all `expose` variables to the `expose` option, also `global` is not works on any envs. For you can you can do:
`expose: { globalName: 'name', export: 'myMethodName'}`

**Pull request closed without merging**
