### PR TITLE
fix(package): add `webpack >= v4.0.0` (`peerDependencies`)

### PR DESCRIPTION
**Pull request by lencioni**
Supersedes #61

### CODE REVIEW

**Comment by lencioni** [comment]
Related work: https://github.com/webpack/webpack.js.org/issues/1852

**Comment by evilebottnawi** [comment]
@michael-ciniawsky need patch release

**Comment by michael-ciniawsky** [comment]
yep, yep I'm releasing all pending packages today, didn't have the time yesterday :)

**Comment by michael-ciniawsky** [comment]
Released in [`v0.7.5`](https://github.com/webpack-contrib/expose-loader/releases/tag/v0.7.5) 🎉

**Pull request merged**
